### ISSUE TITLE
2024 상반기 회고글에 댓글 기능 이슈가 있는것 같습니다.

### ISSUE THREAD

**Issue by KittelLee** [marshallku/marshallku-blog-frontend#3]
Link of the post: https://marshallku.com/chat/2024-상반기-회고

안녕하세요! 블로그(2024상반기회고 게시물)에 댓글을 남겼는데 보이지 않는것 같습니다.!
다른글에 댓글은 잘보이는것 같습니다.

**Comment by marshallku** [comment]
안녕하세요~ 이슈 제보해 주셔서 감사합니다.
백엔드쪽 로그를 봐도 별다른 에러 로그가 보이지 않아서, 아마 유효성 검사를 통과하지 못하셨을 수도 있을 것 같네요.
관련해선 매 댓글 작성 시도마다 로그가 남도록 로그를 보강해 보도록 하겠습니다!

테스트로 해당 글에 댓글을 남겨보니 정상적으로 남겨지는데, 혹시 댓글을 어떻게 남기셨는지 알려주실 수 있을까요?

**Comment by KittelLee** [comment]
블로그 하단에 이름, 주소, 이메일을 입력하고 댓글을 입력했습니다.
마지막으로 우측하단에 submit으로 보이는 버튼을 클릭했는데 refresh되면서 반영이 되질않습니다.

개발자도구-네트워크를 확인해보니 빈배열로 넘어간것 같기도 하고
개발자도구-콘솔을 확인해보니 Warning문제인것 같기도 합니다.

혹시몰라 내용첨부해드립니다.
`Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.`

Privacy notice

This notice and our privacy notice describe how Chrome DevTools handles your data. Please read them carefully.

Chrome DevTools uses the console message, associated stack trace, related source code, and the associated network headers as input data. When you use "Understand this message", Google collects this input data, generated output, related feature usage information, and your feedback. Google uses this data to provide, improve, and develop Google products and services and machine learning technologies, including Google's enterprise products such as Google Cloud.

To help with quality and improve our products, human reviewers may read, annotate, and process the above-mentioned input data, generated output, related feature usage information, and your feedback. Please do not include sensitive (e.g., confidential) or personal information that can be used to identify you or others in your prompts or feedback. Your data will be stored in a way where Google cannot tell who provided it and can no longer fulfill any deletion requests and will be retained for up to 18 months. We may refrain from collecting data to improve our product if your Google account is managed by an organization and depending on your region.

**Comment by marshallku** [comment]
정상적으로 동작했으면 화면이 refresh되지 않아야 하는데, 자바스크립트가 제대로 동작하지 않는 게 문제일 것 같네요.
React Query Dev Tools같은 걸 사용하시면 React 코드가 비정상적으로 동작할 수 있습니다.
혹시 콘솔에 에러 로그는 없을까요?

**Comment by KittelLee** [comment]
React Query Dev Tools은 없고 익스텐션으로 React Developer Tools 사용중입니다.
콘솔에러는 없고 warning중에 아까 위에 보내드린 내용과 요소에 자동완성이 없다는 내용 이렇게 2개만 보이고 있습니다.

**Comment by marshallku** [comment]
사용하시는 OS / 브라우저 정보도 말씀해주실 수 있을까요?

**Comment by KittelLee** [comment]
Mac os Sonoma 이용중이며 크롬이용중입니다!

**Comment by marshallku** [comment]
혹시 해당 글에서만 이슈가 발생하나요...?
말씀하신 에러는 정상적으론 발생할 수가 없는 에러라 뭔가 이상하네요...관련한 케이스가 생길 수 있는지 좀 더 확인해 보겠습니다

**Comment by KittelLee** [comment]
호텔델루나 전시회 다녀오신 게시물에도 댓글을 남겨보았습니다만
`POST https://api.marshallku.com/comment/create 400 (Bad Request)` 라고 콘솔에러가 찍혀있습니다.
의아한건 콘솔에러 끝에 2024-상반기-회고:1 이라고 출력이 됩니다. 분명 호텔델루나 전시회게시글에다가 댓글을 달았는데 말입니다.

네트워크탭에서는
<img width="604" alt="스크린샷 2024-09-18 오후 9 28 29" src="https://github.com/user-attachments/assets/984770cf-23a1-479f-8658-594118d1e415">
다음과 같이 에러가 발생하였고 Response에는 `{"message":"올바른 URL을 입력해 주세요.","error":"Bad Request","statusCode":400}`라고 출력되고 있습니다.

**Comment by marshallku** [comment]
아, 아마 주소창에 올바른 url 형식을 입력하지 않으신 게 이슈인 것 같습니다.
`https://example.com`과 같이 완전한 형식의 주소를 입력해 보시겠어요?

**Comment by KittelLee** [comment]
혹시.. 댓글폼에 주소가` 경기도 ~~` 이런주소가 아니였나요..?
자동완성에 `경기도~~` 이런주소가 떠서 현재 살고있는 주소인줄알았습니다.

**Comment by KittelLee** [comment]
주소에 제 깃허브url을 넣으니 동작합니다!
placeholder로 `https://example.com` 이러한 양식을 넣으면 좋을 것 같아 감히 제안드립니다.!

**Comment by marshallku** [comment]
넵 확인해 주셔서 감사합니다~
Bad Request시 알림이랑, placeholder 등 UX를 개선해 보겠습니다!

**Comment by KittelLee** [comment]
넵 감사합니다!
